### PR TITLE
Added direct RGB mapping to makeTensorStream tool

### PR DESCRIPTION
**Pull request by lolz0r**
An additional param has been added to the command line. Set to 'true' if you wish for your label images to be interpreted as a direct RGB images instead of being filtered through pre-defined classes.

### CODE REVIEW

**Comment by lolz0r** [comment]
When I attempt to train the default kitti net using DBs generated with this code I see an error:

INF [ System::Init(68) ] CN24 version 06206bfbe88095f4dca46506a7fe06ee497d6e76 refs/heads/stable
INF [ System::Init(69) ] Copyright (C) 2015 Clemens-Alexander Brust
INF [ System::Init(70) ] For licensing information, see the LICENSE file included with this project.
DBG [ System::Init(75) ] Executable path: /home/lolz0r/cn24/build/
INF [ System::Init(99) ] Could not find a config file.
INF [ CLHelper::Init(200) ] Using OpenCL device: GeForce GTX 960
INF [ CLHelper::Init(201) ] Image support: Yes
INF [ CLHelper::Init(202) ] Max work group size: 0
INF [ CLHelper::Init(213) ] Creating OpenCL context...
INF [ CLHelper::Init(224) ] Creating OpenCL command queue...
DBG [ CLHelper::CreateProgram(350) ] Compiling kernels/crossCorrelation.cl
DBG [ CLHelper::CreateProgram(350) ] Compiling kernels/biasedConvolution.cl
DBG [ CLHelper::CreateProgram(350) ] Compiling kernels/fullConvolution.cl
DBG [ CLHelper::CreateProgram(350) ] Compiling kernels/foldWeights.cl
DBG [ CLHelper::CreateProgram(350) ] Compiling kernels/biasedMatrixVector.cl
DBG [ CLHelper::CreateProgram(350) ] Compiling kernels/biasGradient.cl
DBG [ CLHelper::CreateProgram(350) ] Compiling kernels/matrixMatrix.cl
DBG [ CLHelper::CreateProgram(350) ] Compiling kernels/maximumPooling.cl
DBG [ CLHelper::CreateProgram(350) ] Compiling kernels/nonLinearFunctions.cl
DBG [ TensorViewer::TensorViewer(57) ] Instance created.
DBG [ ConfigurableFactory::ConfigurableFactory(57) ] Adding convolutional layer to receptive field (7,7)
DBG [ ConfigurableFactory::ConfigurableFactory(64) ] Convolutional layer
DBG [ ConfigurableFactory::ConfigurableFactory(66) ] Adding maxpooling layer to receptive field (2,2)
DBG [ ConfigurableFactory::ConfigurableFactory(57) ] Adding convolutional layer to receptive field (5,5)
DBG [ ConfigurableFactory::ConfigurableFactory(57) ] Adding convolutional layer to receptive field (5,5)
DBG [ main(78) ] Optimal settings: LR: 0.0001, GM: 0.003, EX: 0.75, SB: 2, PB: 2, L1: 0.001, L2: 0.0005, MM: 0.9
INF [ main(84) ] Using fully convolutional training
DBG [ TensorStreamDataset* Conv::TensorStreamDataset::CreateFromConfiguration(328) ] Loading dataset with 1 classes
DBG [ TensorStreamDataset* Conv::TensorStreamDataset::CreateFromConfiguration(329) ] Training tensor: ~/cn24/build/cn24DB/DATASET_TRAIN.Tensor
DBG [ TensorStreamDataset* Conv::TensorStreamDataset::CreateFromConfiguration(330) ] Testing tensor: ~/cn24/build/cn24DB/DATASET_TEST.Tensor
DBG [ TensorStreamDataset::TensorStreamDataset(32) ] Instance created.
ERR [ Tensor::Deserialize(253) ] Cannot deserialize from this stream!
DBG [ TensorStreamDataset::TensorStreamDataset(54) ] 0 training tensors
ERR [ Tensor::Deserialize(253) ] Cannot deserialize from this stream!
DBG [ TensorStreamDataset::TensorStreamDataset(73) ] 0 testing tensors
DBG [ DatasetInputLayer::DatasetInputLayer(31) ] Instance created.
DBG [ DatasetInputLayer::DatasetInputLayer(41) ] Using loss sampling probability: 0.25
DBG [ DatasetInputLayer::DatasetInputLayer(47) ] Total samples: 0
DBG [ Net::AddLayer(59) ] Layer 0 output 0: (0s@0x0x0m)
DBG [ Net::AddLayer(59) ] Layer 0 output 1: (0s@0x0x0m)
DBG [ Net::AddLayer(59) ] Layer 0 output 2: (0s@0x0x0m)
DBG [ Net::AddLayer(59) ] Layer 0 output 3: (0s@0x0x0m)
DBG [ Net::AddLayer(73) ] Layer 0 added.
DBG [ Net::AddLayer(77) ] Layer 0 is OpenCL aware
DBG [ Net::AddLayer(87) ] Layer 0 added as training layer.
DBG [ ResizeLayer::ResizeLayer(23) ] Instance created, border size: (22, 22)
DBG [ Net::AddLayer(37) ] Layer 1 input: layer 0, output 0
DBG [ Net::AddLayer(59) ] Layer 1 output 0: (0s@0x0x0m)
ERR [ ResizeLayer::Connect(66) ] FATAL: Dimensions don't match!
terminate called after throwing an instance of 'std::runtime_error'
  what():  See log for details.
Aborted (core dumped)

I will investigate tomorrow to see if its the generated DBs or something else.

**Comment by clrokr** [comment]
Hi,
thanks for the PR! I still need to add some bits to the .set parsers so that all the tools know about regression vs. classification.
As for your error, this usually means that CN24 could not read or find the Tensor files. It may also mean that one of the dimensions (probably the "maps" dimension) is zero when it needs to be 3. What does your "classes" section of the configuration look like?
While I'm working on the parsers, I recommend something like this:
```
classes=3
red
green
blue

colors
0xFF0000
0x00FF00
0x0000FF
```

**Comment by lolz0r** [comment]
Nice! I hope to see the updates for regression soon!

**Comment by clrokr** [comment]
Hi,
please tell me if and how you want to be listed in the CONTRIBUTORS file :)

**Comment by lolz0r** [comment]
Sure!

**Comment by clrokr** [comment]
Do you want your full name in there?

**Comment by lolz0r** [comment]
Just lolz0r ;)

**Pull request merged**
